apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cronjob-py
  namespace: "default"
data:
  cronjob.py: |
    import os
    from bson import ObjectId
    from pymongo.mongo_client import MongoClient
    from datetime import datetime, timezone

    uri = os.environ["MONGO_URI"]
    client = MongoClient(os.environ["MONGO_URI"])

    current_date = datetime.now(timezone.utc).replace(microsecond=0)
    print(f"Current date (formatted): {current_date}")

    try:
        db = client.get_database("admin")
        collections = db["letters"]
        print(f"Connected to MongoDB.")

        letters_to_update = collections.find({"sendAt": {"$lte": current_date}})
        print("update letters")

        for letter in letters_to_update:
            print(letter)
            result = collections.update_one({"_id": ObjectId(letter["_id"])}, {"$set": {"isReadable": True}})
        print(f"Successfully updated letters.")
    except Exception as e:
        print(f"Error: {e}")