apiVersion: v1
kind: Secret
metadata:
  name: mongodb-uri
  namespace: default
type: Opaque
data:
  URI: "bW9uZ29kYjovL3Jvb3Q6cm9vdEBrdWJleWllbGQtbW9uZ29kYjoyNzAxNy9hZG1pbj9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkK" 