kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeyield-mongodb
  namespace: "default"
  annotations:
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"